Repository 2023WinterBootCamp-Team-L/CloverFeed, pull requests merged in 2024-01, with the labels that each got.

#10 chore/#9 백엔드 dockerfile 수정
  backend/Dockerfile
Labels: BE, 수정

#12 chore:frontend 초기세팅
  backend/Dockerfile
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: FE

#15 Chore/#11 Frontend Dockerfile 추가
  Dockerfile
  frontend/.package-lock.json
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: FE

#16 Chore/#11 Frontend Dockerfile 추가
  Dockerfile
  frontend/.package-lock.json
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: FE

#18 chore: 프론트엔드 dockerfile 수정
  frontend/Dockerfile
  frontend/vite.config.ts
Labels: FE

#21 Design/#20
  Dockerfile
  frontend/Dockerfile
  frontend/src/App.tsx
  frontend/src/assets/clover.svg
  frontend/src/components/Background.tsx
  frontend/src/main.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: FE

#28 Chore: tailwind 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/tailwind.config.js
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: FE

#35 feat: QueryMain, QueryStart 퍼블리싱 / ChangePage 기능 구현
  frontend/src/components/ChangePage.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryStart.tsx
Labels: Must Have, FE, 기능구현

#39 Feat/#23 query main,query start,query list
  frontend/src/App.tsx
  frontend/src/assets/backarrow.svg
  frontend/src/assets/nextarrow.svg
  frontend/src/assets/plus.svg
  frontend/src/assets/querystart.svg
  frontend/src/components/BackButton.tsx
  frontend/src/components/ChangePage.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/QuestAdd.tsx
  frontend/src/components/QuestButton.tsx
  frontend/src/pages/QueryList.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryStart.tsx
  frontend/src/tailwind.config.js
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#46 Design/#20
  .gitignore
  frontend/src/App.tsx
  frontend/src/assets/PMPO.svg
  frontend/src/assets/개발자.svg
  frontend/src/assets/기타직무.svg
  frontend/src/assets/기획자.svg
  frontend/src/assets/디자이너.svg
  frontend/src/components/LinkButton.tsx
  frontend/src/components/ProgressBar.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/LinkStart.tsx
  frontend/src/pages/LinkTag1.tsx
Labels: Must Have, FE, 기능구현

#55 Feat/#41 query add,query share
  frontend/src/components/AddButton.tsx
  frontend/src/components/AnswerOption.tsx
  frontend/src/components/BackButton.tsx
  frontend/src/components/BaseQuest.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/QuestionList.tsx
  frontend/src/components/ShortButton.tsx
  frontend/src/components/Toggle.tsx
  frontend/src/pages/QueryAdd.tsx
  frontend/src/pages/QueryList.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
  frontend/src/tailwind.config.js
  frontend/tailwind.config.js
Labels: Must Have, FE, 기능구현

#56 feat: 질문폼 모달창 구현 완료
  frontend/src/components/Toggle.tsx
  frontend/src/pages/QueryList.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
Labels: Must Have, FE, 기능구현

#58 feat: Chart 퍼블리싱
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Line.tsx
  frontend/src/pages/Chart.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#63 Feat/#62 tag component
  frontend/package.json
  frontend/src/components/Tag.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#64 fix: GreenButton 수정
  frontend/src/components/GreenButton.tsx
Labels: Must Have, FE, 기능구현

#72 Feat/#68
  .idea/inspectionProfiles/Project_Default.xml
  backend/cloverfeed/serializers.py
  backend/cloverfeed/urls.py
  backend/cloverfeed/views.py
Labels: BE, Must Have, 기능구현

#78 Feat/#70 작성한 질문 목록 확인
  backend/cloverfeed/migrations/0006_remove_authuser_user_id.py
  backend/cloverfeed/models.py
  backend/cloverfeed/serializers.py
  backend/cloverfeed/views.py
Labels: BE, Must Have, 기능구현

#79 Feat/#67 피드백 폼 유무 조회
  backend/cloverfeed/migrations/0005_alter_authuser_id.py
  backend/cloverfeed/urls.py
  backend/cloverfeed/views.py
  backend/config/settings.py
Labels: BE, Must Have, 기능구현

#81 feat: 검색 기능 구현 및 디자인 수정
  frontend/src/components/FeedbackBox.tsx
  frontend/src/components/Searchbutton.tsx
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/Search.tsx
Labels: Must Have, FE, 기능구현

#82 Feat/#77 progressbar
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/LinkPosition.tsx
Labels: Must Have, FE, 기능구현

#86 Feat/#47
  frontend/package.json
  frontend/public/assets/TagIcon/결단력.svg
  frontend/public/assets/TagIcon/경청하는.svg
  frontend/public/assets/TagIcon/계획적인.svg
  frontend/public/assets/TagIcon/공감능력.svg
  frontend/public/assets/TagIcon/관대한.svg
  frontend/public/assets/TagIcon/규칙준수.svg
  frontend/public/assets/TagIcon/긍정적인.svg
  frontend/public/assets/TagIcon/기획력.svg
  frontend/public/assets/TagIcon/꼼꼼함.svg
  frontend/public/assets/TagIcon/끈기.svg
  frontend/public/assets/TagIcon/눈치빠른.svg
  frontend/public/assets/TagIcon/도전적인.svg
  frontend/public/assets/TagIcon/리더쉽.svg
  frontend/public/assets/TagIcon/문제분석.svg
  frontend/public/assets/TagIcon/박학다식.svg
  frontend/public/assets/TagIcon/배려심.svg
  frontend/public/assets/TagIcon/분위기메이커.svg
  frontend/public/assets/TagIcon/사교성이좋은.svg
  frontend/public/assets/TagIcon/성실함.svg
  frontend/public/assets/TagIcon/센스있는.svg
  frontend/public/assets/TagIcon/위기대처능력.svg
  frontend/public/assets/TagIcon/의견다양성.svg
  frontend/public/assets/TagIcon/적극적인.svg
  frontend/public/assets/TagIcon/전략적인.svg
  frontend/public/assets/TagIcon/정보수집.svg
  frontend/public/assets/TagIcon/주도적인.svg
  frontend/public/assets/TagIcon/책임감.svg
  frontend/public/assets/TagIcon/추진력.svg
  frontend/public/assets/TagIcon/협력적인.svg
  frontend/public/assets/TagIcon/효율적인.svg
  frontend/src/App.tsx
  frontend/src/components/Tag.tsx
  frontend/src/pages/LinkAnswer1.tsx
  frontend/src/pages/LinkAnswer2.tsx
  frontend/src/pages/LinkOpti.tsx
  frontend/src/pages/LinkTag1.tsx
  frontend/src/pages/LinkTag2.tsx
Labels: Must Have, FE, 기능구현

#94 Feat/#85 직군별피드백목록확인api
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/BluefeedButton.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/PurplefeedButton.tsx
  frontend/src/components/Tag.tsx
  frontend/src/pages/Atest.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#99 fix: apiURI 수정
  frontend/package.json
  frontend/src/pages/FeedBackList.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#105 feat:받은 피드백답변(주관식) 내용 검색
  backend/cloverfeed/serializers.py
  backend/cloverfeed/urls.py
  backend/cloverfeed/views.py
Labels: BE, Shoud Have, 기능구현

#113 feat: 피드백 질문 목록 작성
  backend/cloverfeed/migrations/0002_alter_feedbackresult_created_at_and_more.py
  backend/cloverfeed/models.py
  backend/cloverfeed/serializers.py
  backend/cloverfeed/views.py
Labels: BE, Must Have, 기능구현

#109 Feat/#84 질문답변 제출 (오류 해결 완~)
  backend/cloverfeed/__pycache__/admin.cpython-312.pyc
  backend/cloverfeed/__pycache__/apps.cpython-312.pyc
  backend/cloverfeed/__pycache__/models.cpython-310.pyc
  backend/cloverfeed/__pycache__/models.cpython-312.pyc
  backend/cloverfeed/__pycache__/serializers.cpython-310.pyc
  backend/cloverfeed/__pycache__/serializers.cpython-312.pyc
  backend/cloverfeed/__pycache__/urls.cpython-310.pyc
  backend/cloverfeed/__pycache__/urls.cpython-312.pyc
  backend/cloverfeed/__pycache__/views.cpython-310.pyc
  backend/cloverfeed/__pycache__/views.cpython-312.pyc
  backend/cloverfeed/migrations/0001_initial.py
  backend/cloverfeed/migrations/0002_alter_feedbackresult_created_at_and_more.py
  backend/cloverfeed/migrations/__pycache__/__init__.cpython-310.pyc
  backend/cloverfeed/migrations/__pycache__/__init__.cpython-312.pyc
  backend/cloverfeed/urls.py
  backend/cloverfeed/views.py
  backend/config/__pycache__/__init__.cpython-312.pyc
  backend/config/__pycache__/settings.cpython-312.pyc
  backend/config/__pycache__/urls.cpython-312.pyc
Labels: BE, Must Have, 기능구현

#111 Feat/#104 워드클라우드디자인
  frontend/package.json
  frontend/src/assets/clovercloud.svg
  frontend/src/components/GreenButton.tsx
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/Atest.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#117 Feat/#85 직군별피드백목록확인api
  frontend/src/pages/Atest.tsx
  frontend/src/pages/FeedBackList.tsx
Labels: Must Have, FE, 기능구현

#122 Feat/#120 migrations 수정
  backend/cloverfeed/__pycache__/models.cpython-310.pyc
  backend/cloverfeed/__pycache__/serializers.cpython-310.pyc
  backend/cloverfeed/__pycache__/urls.cpython-310.pyc
  backend/cloverfeed/__pycache__/views.cpython-310.pyc
  backend/cloverfeed/migrations/0001_initial.py
  backend/cloverfeed/migrations/__pycache__/__init__.cpython-310.pyc
  backend/cloverfeed/migrations/__pycache__/__init__.cpython-312.pyc
  backend/cloverfeed/models.py
Labels: BE, Shoud Have, 수정

#119 fix: 질문 목록 확인 시 폼 없을 때 예외처리
  backend/cloverfeed/serializers.py
  backend/cloverfeed/views.py
Labels: BE, Must Have, 수정

#126 Feat/#96 특정피드백상세내용확인api 연동
  backend/cloverfeed/serializers.py
  frontend/src/components/Tag.tsx
  frontend/src/pages/FeedBackResult.tsx
Labels: Must Have, FE, 기능구현

#134 design: 퍼블리싱 및 API 연동 데이터 보완
  frontend/src/App.tsx
  frontend/src/components/FeedbackBox.tsx
  frontend/src/components/TagAnswer.tsx
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
  frontend/src/pages/Search.tsx
Labels: Must Have, FE, 디자인

#135 chore: MySQL Health Check
  docker-compose.yml
Labels: Shoud Have, DevOps

#148 Feat/#130 직군별피드백개수확인api
  frontend/src/App.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/FeedCount.tsx
  frontend/src/components/getCategotyText.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
Labels: Must Have, FE, 기능구현

#153 Chore/#152 api프록시설정, Feat/#83 회원가입, 로그인 api 연동
  backend/cloverfeed/serializers.py
  frontend/my-react-app/package.json
  frontend/package.json
  frontend/src/components/GologinButton.tsx
  frontend/src/components/LoginModal.tsx
  frontend/src/components/OverlapButton.tsx
  frontend/src/components/SignupAnswer.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Signup.tsx
Labels: Must Have, FE, 기능구현

#154 fix: api URI 수정
  frontend/src/components/FeedCount.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
Labels: Must Have, FE, 기능구현

#156 fix: api url 수정
  frontend/src/App.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/FeedCount.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Mainpage.tsx
Labels: Must Have, FE, 기능구현

#164 Feat/#149 피드백답변저장
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Answer/AnswerStore.tsx
  frontend/src/components/Answer/ChoiceButton.tsx
  frontend/src/components/Answer/ChoicePart.tsx
  frontend/src/components/Answer/ShortPart.tsx
  frontend/src/main.tsx
  frontend/src/pages/LinkOpti.tsx
  frontend/src/pages/LinkPage/AnswerCheck.tsx
  frontend/src/pages/LinkPage/LinkAnswer.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/QueryAdd.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 기능구현

#168 Design/#133 퍼블리싱보완
  frontend/src/assets/charticon.svg
  frontend/src/assets/fonts/Pretendard-Bold.otf
  frontend/src/assets/fonts/Pretendard-Medium.otf
  frontend/src/assets/researchicon.svg
  frontend/src/assets/shareicon.svg
  frontend/src/components/ChangePage.tsx
  frontend/src/components/ChartButton.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/FeedbackAnswerInput.tsx
  frontend/src/components/GologinButton.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/HomeButton.tsx
  frontend/src/components/Line.tsx
  frontend/src/components/LinkButton.tsx
  frontend/src/components/LoginModal.tsx
  frontend/src/components/ResearchButton.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/components/ShortButton.tsx
  frontend/src/components/SignupAnswer.tsx
  frontend/src/components/SuccessButton.tsx
  frontend/src/components/Tag.tsx
  frontend/src/components/TagAnswer.tsx
  frontend/src/components/getCategotyText.tsx
  frontend/src/index.css
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/LinkAnswer1.tsx
  frontend/src/pages/LinkAnswer2.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/LinkOpti.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/LinkStart.tsx
  frontend/src/pages/LinkTag1.tsx
  frontend/src/pages/LinkTag2.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
  frontend/src/pages/Signup.tsx
  frontend/tailwind.config.js
Labels: Must Have, FE, 디자인

#170 Feat/#165 피드백질문에답변제출api
  frontend/src/App.tsx
  frontend/src/components/Answer/AnswerStore.tsx
  frontend/src/components/Answer/ChoicePart.tsx
  frontend/src/components/Answer/ShortPart.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkPage/LinkAnswer.tsx
Labels: Must Have, FE, 기능구현

#178 design: 세부사항 수정
  frontend/src/components/FeedbackAnswerInput.tsx
  frontend/src/components/TagAnswer.tsx
  frontend/src/pages/Mainpage.tsx
Labels: Must Have, FE, 디자인

#179 Feat/#142 검색api연동
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/Search.tsx
Labels: FE, Shoud Have, 기능구현

#182 Feat/#128 피드백 질문 목록 작성 API 연동
  frontend/src/App.tsx
  frontend/src/atoms.ts
  frontend/src/components/AddButton.tsx
  frontend/src/components/AnswerOption.tsx
  frontend/src/components/AnswerOptionList.tsx
  frontend/src/components/BaseQuest.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/PopupQuestion.tsx
  frontend/src/components/Question/QuestionStore.tsx
  frontend/src/components/QuestionList.tsx
  frontend/src/components/QuestionUpdate.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/components/Toggle.tsx
  frontend/src/pages/LinkPage/AnswerCheck.tsx
  frontend/src/pages/QueryAdd.tsx
  frontend/src/pages/QueryList.tsx
Labels: Must Have, FE, 기능구현

#177 Feat/#176 ChatGPT 연동 전체 피드백 요약, 워드클라우드 수정
  backend/Dockerfile
  backend/cloverfeed/__pycache__/admin.cpython-312.pyc
  backend/cloverfeed/__pycache__/apps.cpython-312.pyc
  backend/cloverfeed/__pycache__/models.cpython-312.pyc
  backend/cloverfeed/apitest.py
  backend/cloverfeed/migrations/0001_initial.py
  backend/cloverfeed/models.py
  backend/cloverfeed/serializers.py
  backend/cloverfeed/urls.py
  backend/cloverfeed/views.py
  backend/config/.env
  backend/config/__pycache__/__init__.cpython-312.pyc
  backend/config/__pycache__/settings.cpython-312.pyc
  backend/config/settings.py
  backend/config/urls.py
  backend/requirements.txt
Labels: BE, Shoud Have, 기능구현

#172 Feat/#157 작성한질문목록확인api
  frontend/atoms/AnswerStore.tsx
  frontend/atoms/QuestionStore.tsx
  frontend/src/App.tsx
  frontend/src/components/Answer/ChoicePart.tsx
  frontend/src/components/Answer/ShortPart.tsx
  frontend/src/index.css
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkAnswer1.tsx
  frontend/src/pages/LinkAnswer2.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkPage/AnswerCheck.tsx
  frontend/src/pages/LinkPage/LinkAnswer.tsx
  frontend/src/pages/QueryAdd.tsx
  frontend/src/pages/QueryList.tsx
  frontend/tsconfig.json
Labels: Must Have, FE, 기능구현

#184 fix: Link 페이지 정리
  frontend/src/App.tsx
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkOpti.tsx
  frontend/src/pages/LinkTag2.tsx
Labels: Must Have, FE, 기능구현

#186 Fix/#185 API userid 파라미터 수정, 질문 내용 조회 시 최신 폼 내용만 받아오도록 수정
  backend/cloverfeed/views.py
Labels: BE, Must Have, 수정

#187 Feat/#183 userid로컬스토리지
  frontend/atoms/AnswerStore.tsx
  frontend/atoms/QuestionStore.tsx
  frontend/src/components/Answer/ChoicePart.tsx
  frontend/src/components/FeedCount.tsx
  frontend/src/components/GologinButton.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryList.tsx
  frontend/src/pages/Search.tsx
Labels: Must Have, FE, 기능구현

#189 Feat/#142 Link 페이지 반응형
  frontend/src/components/BackButton.tsx
  frontend/src/components/FeedbackAnswerInput.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/HomeButton.tsx
  frontend/src/components/Tag.tsx
  frontend/src/pages/LinkAnswer1.tsx
  frontend/src/pages/LinkAnswer2.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/LinkOpti.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/LinkStart.tsx
  frontend/src/pages/LinkTag1.tsx
  frontend/src/pages/LinkTag2.tsx
Labels: FE, 디자인

#190 Feat/#165 피드백질문에답변제출api
  frontend/atoms/AnswerStore.tsx
  frontend/atoms/QuestionStore.tsx
  frontend/src/assets/fonts/Pretendard-Bold.otf
  frontend/src/assets/fonts/Pretendard-Bold.woff
  frontend/src/assets/fonts/Pretendard-Medium.otf
  frontend/src/assets/fonts/Pretendard-Medium.woff
  frontend/src/components/Answer/CategotyPart.tsx
  frontend/src/components/Answer/ChoiceButton.tsx
  frontend/src/components/Answer/ChoicePart.tsx
  frontend/src/components/Answer/TagPart.tsx
  frontend/src/components/Popup.tsx
  frontend/src/index.css
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkAnswer1.tsx
  frontend/src/pages/LinkAnswer2.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/LinkOpti.tsx
  frontend/src/pages/LinkPage/AnswerCheck.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/LinkStart.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryAdd.tsx
  frontend/src/pages/QueryList.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
Labels: Must Have, FE, 기능구현

#194 Fix/#192 태그 선택 시 색상 관련 문제 수정
  backend/cloverfeed/urls.py
  frontend/package.json
  frontend/public/assets/TagIcon/효율적인.svg
  frontend/src/Api/LinkAPI/PositionApi.tsx
  frontend/src/Api/QueryApi.tsx/QueryListApi.tsx
  frontend/src/assets/결단력.png
  frontend/src/assets/경청하는.png
  frontend/src/assets/계획적인.png
  frontend/src/assets/공감능력.png
  frontend/src/assets/관대한.png
  frontend/src/assets/규칙준수.png
  frontend/src/assets/긍정적인.png
  frontend/src/assets/기획력.png
  frontend/src/assets/꼼꼼함.png
  frontend/src/assets/끈기.png
  frontend/src/assets/눈치빠른.png
  frontend/src/assets/도전적인.png
  frontend/src/assets/리더쉽.png
  frontend/src/assets/문제분석.png
  frontend/src/assets/박학다식.png
  frontend/src/assets/배려심.png
  frontend/src/assets/분위기메이커.png
  frontend/src/assets/사교성이좋은.png
  frontend/src/assets/성실함.png
  frontend/src/assets/센스있는.png
  frontend/src/assets/위기대처능력.png
  frontend/src/assets/의견다양성.png
  frontend/src/assets/적극적인.png
  frontend/src/assets/전략적인.png
  frontend/src/assets/정보수집.png
  frontend/src/assets/주도적인.png
  frontend/src/assets/책임감.png
  frontend/src/assets/추진력.png
  frontend/src/assets/협력적인.png
  frontend/src/assets/효율적인.png
  frontend/src/components/AnswerForm.tsx
  frontend/src/components/ExceedPopup.tsx
  frontend/src/components/Tag.tsx
  frontend/src/pages/LinkAnswer1.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/LinkTag1.tsx
  frontend/src/pages/LinkTag2.tsx
  frontend/yarn.lock
Labels: Must Have, FE, 수정

#197 design: 검색 페이지 퍼블리싱 보완
  frontend/src/components/Searchbutton.tsx
  frontend/src/pages/Search.tsx
Labels: Must Have, FE, 디자인

#199 fix: QuestionStore 질문 목록 수정
  frontend/atoms/QuestionStore.tsx
Labels: Must Have, FE, 수정

#196 Feat/#191 전체키워드추출및요약api
  frontend/src/components/FeedButton.tsx
  frontend/src/components/FeedCount.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/Mainpage.tsx
Labels: FE, Shoud Have, 기능구현

#203 Feat/#26-메인페이지 반응형 완료
  frontend/src/components/GreenButton.tsx
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryAdd.tsx
  frontend/src/pages/QueryList.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
  frontend/tailwind.config.js
Labels: Must Have, FE, 디자인

#211 Feat/#130 직군별피드백개수확인api
  frontend/src/components/FeedButton.tsx
  frontend/src/components/FeedCount.tsx
  frontend/src/pages/Mainpage.tsx
Labels: Must Have, FE, 기능구현

#214 Design/#188 반응형 디자인
  frontend/src/App.css
  frontend/src/components/GologinButton.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/LoginModal.tsx
  frontend/src/components/SuccessButton.tsx
  frontend/src/components/TagAnswer.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Signup.tsx
Labels: FE, 디자인

#215 Design 주간발표
  frontend/src/pages/Mainpage.tsx
Labels: FE, 디자인

#219 Feat/#96 특정피드백상세내용확인api
  backend/cloverfeed/urls.py
  backend/cloverfeed/views.py
  frontend/src/App.tsx
  frontend/src/components/FeedbackBox.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/Search.tsx
Labels: BE, Must Have, FE, 기능구현

#220 fix: 태그 코드 수정
  frontend/src/components/TagAnswer.tsx
  frontend/src/pages/FeedBackList.tsx
Labels: Must Have, FE, 수정

#225 Design/#218 페이지 반응형 디자인
  frontend/src/App.css
  frontend/src/components/GologinButton.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/HomeButton.tsx
  frontend/src/components/SuccessButton.tsx
  frontend/src/pages/Chart.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/LinkPosition.tsx
  frontend/src/pages/LinkStart.tsx
  frontend/src/pages/LinkTag1.tsx
  frontend/src/pages/LinkTag2.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Signup.tsx
Labels: FE, 디자인

#223 fix: 대답 2번 제출 수정, pmpo 링크 연결 수정
  frontend/atoms/QuestionStore.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/TagAnswer.tsx
  frontend/src/main.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/QueryList.tsx
Labels: Must Have, FE, 기능구현, 수정, 디자인

#230 Feat/#165 피드백질문에답변제출api
  frontend/atoms/AnswerStore.tsx
  frontend/atoms/TagStore.tsx
  frontend/src/components/Answer/TagPart.tsx
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkStart.tsx
Labels: Must Have, FE, 수정

#221 Feat/#57 chart
  frontend/src/pages/Chart.tsx
Labels: Must Have, FE, 수정

#222 Design/#133 퍼블리싱보완
  frontend/src/components/FeedbackBox.tsx
  frontend/src/components/Searchbutton.tsx
  frontend/src/components/Toggle.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/Search.tsx
Labels: FE, 수정, 디자인

#224 fix: 로그인페이지에 피드백폼 유무 조회 api 연동
  frontend/src/components/GologinButton.tsx
  frontend/src/pages/Login.tsx
Labels: Must Have, FE, 기능구현

#226 fix: form_id 데이터 불러오기
  backend/cloverfeed/views.py
  frontend/atoms/AnswerStore.tsx
  frontend/atoms/QuestionStore.tsx
  frontend/atoms/TagStore.tsx
  frontend/public/assets/TagIcon/창의적인.svg
  frontend/src/assets/창의적인.png
  frontend/src/components/Answer/ShortPart.tsx
  frontend/src/components/Answer/TagPart.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/TagAnswer.tsx
  frontend/src/main.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkStart.tsx
  frontend/src/pages/QueryList.tsx
Labels: Must Have, FE, 수정

#231 Feat/#77 progressbar
  frontend/src/components/ProgressBar.tsx
  frontend/src/pages/LinkAnswer.tsx
Labels: FE, 기능구현, Won't Have

#239 Feat/#209 차트 칭찬할 점, 개선할 점 뺌
  frontend/src/pages/Chart.tsx
Labels: Must Have, FE, 기능구현

#242 Fix/#240 피드백 폼 제출 오류 수정
  frontend/src/pages/LinkAnswer.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkMain.tsx
  frontend/src/pages/LinkStart.tsx
Labels: Must Have, FE, 수정

#235 Feat/#234 태그 아이콘 깨짐/검색페이지 PMPO 주소 수정
  frontend/src/components/FeedbackBox.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
Labels: FE, 수정

#238 fix: 로그아웃 주소 수정
  frontend/src/pages/Mainpage.tsx
Labels: FE, 수정

#244 Feat/#241 눈치빠른 태그 및 줄 바꿈 수정
  frontend/atoms/TagStore.tsx
  frontend/src/pages/LinkAnswer.tsx
Labels: FE, 수정

#245 fix: 검색페이지 중복 데이터 필터링
  frontend/src/pages/Search.tsx
Labels: Must Have, FE, 수정

#246 fix: 빌드 오류들 수정
  frontend/src/components/AnswerOptionList.tsx
  frontend/src/components/ShortButton.tsx
  frontend/src/pages/Chart.tsx
Labels: Must Have, FE, 수정

#247 Design/#218 애니메이션 디자인
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/assets/clovercloud.svg
  frontend/src/components/AddButton.tsx
  frontend/src/components/AnswerOption.tsx
  frontend/src/components/BackButton.tsx
  frontend/src/components/ChartButton.tsx
  frontend/src/components/FeedButton.tsx
  frontend/src/components/GologinButton.tsx
  frontend/src/components/GreenButton.tsx
  frontend/src/components/HomeButton.tsx
  frontend/src/components/LogoutButton.tsx
  frontend/src/components/ResearchButton.tsx
  frontend/src/components/Searchbutton.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/components/SuccessButton.tsx
  frontend/src/components/XButton.tsx
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryList.tsx
  frontend/tailwind.config.js
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: FE, 디자인

#250 fix: TagAnswer 컴포넌트 수정
  frontend/src/components/FeedbackBox.tsx
  frontend/src/components/TagAnswerList.tsx
  frontend/src/pages/FeedBackList.tsx
  frontend/src/pages/FeedBackResult.tsx
Labels: FE, 수정

#249 fix: login, query화면 중앙배열
  frontend/src/App.tsx
  frontend/src/components/wordcloud.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/LinkFinish.tsx
  frontend/src/pages/LinkTag1.tsx
  frontend/src/pages/LinkTag2.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/src/pages/QueryMain.tsx
  frontend/src/pages/QueryShare.tsx
  frontend/src/pages/QueryStart.tsx
  frontend/src/pages/Signup.tsx
Labels: FE, 디자인

#251 design:비밀번호*표시
  frontend/package.json
  frontend/src/components/SignupAnswer.tsx
  frontend/src/pages/Gosignup.tsx
  frontend/src/pages/Mainpage.tsx
  frontend/yarn.lock
Labels: FE, 디자인
